# Generated by Django 5.2.11 on 2026-04-25 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0005_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feed_id', models.AutoField(primary_key=True, serialize=False)),
                ('star_feedback', models.TextField(max_length=900)),
                ('star_rating', models.CharField(max_length=100, null=True)),
                ('star_Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexapp.userprofile')),
            ],
        ),
    ]
