# Generated by Django 5.2.11 on 2026-05-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0006_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
    ]
