# Generated by Django 5.2.11 on 2026-07-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0008_alter_userprofile_email_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
