# Generated by Django 5.2.11 on 2026-07-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0009_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='course_images/'),
        ),
    ]
