# Generated by Django 5.2.11 on 2026-07-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0010_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
