# Generated by Django 5.2.11 on 2026-07-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0011_userprofile_password_reset_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
